module.exports = {
  pathPrefix: '/',
  title: 'CodeWithIhwan',
  titleAlt: 'Code With Ihwan',
  description: 'Website tempat belajar mobile programming berbahasa Indonesia lengkap. membahas teknologi native untuk Android, iOS dan Hybrid dengan Flutter.',
  url: 'https://codewith.ihwan.id',
  siteUrl: 'https://codewith.ihwan.id',
  siteLanguage: 'id',
  logo: 'static/logo/logo.png',
  banner: 'static/logo/banner.png',
  favicon: 'static/logo/favicon.png',
  shortName: 'IhwanID',
  author: 'Ihwan',
  themeColor: '#3e7bf2',
  backgroundColor: '#d3e0ff',
  twitter: '@Ihwan_ID',
};
